export const LOGIN = 'team-manager/session/LOGIN'
export const LOGIN_REQUESTED = 'team-manager/session/LOGIN_REQUESTED'
export const LOGIN_SUCESS = 'team-manager/session/LOGIN_SUCESS'
export const LOGIN_ERROR = 'team-manager/session/LOGIN_ERROR'
export const API_URL = 'http://localhost:9000'
export const API_LOGIN_ENDPOINT = '/api/users/login'   
export const API_SIGNUP_ENDPOINT = '/api/users/signup'   
